# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odhuTeAvWzedlk_lAgKSDHDZMYGJGF7F
"""

def kasallik_tashxisi(belgi):
    if belgi == "istima":
         return "Parasetamol iching"
    elif belgi == "bosh og`rig`i":
         return "Trimol iching"
    elif belgi == "gripp":
         return "Taylon hot iching"
    elif belgi == "davleniya":
         return "Enap iching"
    elif belgi == "qorin og`rig`i":
         return "Espumisan iching"
    elif belgi == "ko`z og`risa":
         return "Vizin iching"
    elif belgi == "Tish og`rig`i":
         return "Parasetamol iching"
    else:
         return "Shifokorga murojaat qiling"
belgi=input("Kasallik belgisini kiriting ")
natija=kasallik_tashxisi(belgi)
print(natija)



































